{{- if and .Values.backend.metrics.enabled .Values.backend.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-metrics
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: erato-app
    erato.ai/scrape-metrics: "true"
    {{- with .Values.backend.metrics.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.backend.metrics.service.addPrometheusAnnotations .Values.backend.metrics.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.backend.metrics.service.addPrometheusAnnotations }}
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: {{ .Values.backend.metrics.service.port | quote }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.backend.metrics.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.backend.metrics.service.type }}
  ports:
    - port: {{ .Values.backend.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: erato-app
{{- end }}
