[file_storage_providers.s3_k8s]
provider_kind = "s3"
max_upload_size_kb = 15360  # 15 MB
config = { endpoint = "http://seaweedfs-s3:8333", bucket = "erato-storage", region = "us-east-1", access_key_id = "admin", secret_access_key = "admin" }

