{{- if .Values.nginxAuth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-auth-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-nginx-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: config
data:
  nginx.conf: |
{{ tpl (.Files.Get "files/nginx.conf") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-auth-js
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-nginx-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: config
data:
  main.js: |
{{ tpl (.Files.Get "files/main.js") . | indent 4 }}
{{- end }}
